version: 2
project_name: lightctl
builds:
  - main: ./cmd/lightctl
    binary: lightctl
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -X github.com/aviadshiber/lightctl/cmd.Version={{.Version}}
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files: [LICENSE, README.md]
nfpms:
  - package_name: lightctl
    homepage: https://github.com/aviadshiber/lightctl
    maintainer: Aviad Shiber
    description: LightRun CLI -- runtime debugging tool
    license: MIT
    formats: [deb, rpm]
brews:
  - repository:
      owner: aviadshiber
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
      branch: "lightctl-{{.Version}}"
      pull_request:
        enabled: true
        base:
          owner: aviadshiber
          name: homebrew-tap
          branch: main
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Version }}"
    directory: Formula
    homepage: "https://github.com/aviadshiber/lightctl"
    description: "LightRun CLI -- runtime debugging tool"
    license: "MIT"
    install: |
      bin.install "lightctl"
    test: |
      system "#{bin}/lightctl", "version"
checksum:
  name_template: checksums.txt
